apiVersion: v1
data:
  asset.id: "0000"
  asset.name: promoter-test-0000
  github.org: crenshaw-dev
  github.url: https://github.com
kind: ConfigMap
metadata:
  labels:
    app: promoter-test-0000
    asset-id: "0000"
  name: promoter-test-0000-config
